version: '3.8'

services:
  todos:
    build: .
    container_name: todos_c
    ports:
      - 3000:3000
    volumes:
      - .:/src
      - /src/node_modules
    networks:
      - todos_network
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongo_c
    ports:
      - 27017:27017
    volumes:
      - mongod:/data
      - /data/node_modules
    networks:
      - todos_network

  redis:
    image: redis:latest
    container_name: redis_c
    ports:
      - 6379:6379
    volumes:
      - redisd:/data
      - /data/node_modules
    networks:
      - todos_network

volumes:
  mongod:
  redisd:
networks:
  todos_network: